name: Docs

on:
  push:
    branches: [ master, 'dev/*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install APT dependencies
      run: |
        sudo apt-get install -y git build-essential apt-utils wget libfreetype6 libpng-dev libopenblas-dev gcc gfortran libsnappy-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry wheel
        poetry install
    - name: Build docs
      run: |
        cd doc && poetry run make html
